apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesStrategicMerge:
- increase-memory.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web-app
  path: add-label.yaml